### ISSUE TITLE
block not pinned error during smoldot restarts

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#488]
REPO: 

Clone: https://github.com/paritytech/substrate-connect/tree/codespace-supreme-space-palm-tree-77974x4wj492pwpq

```sh
corepack pnpm i
cd packages/light-client-experimental
corepack pnpm turbo build
pnpm dlx tsx ./scripts/testing.ts
```

Then wait for the **first restart** to see if the error occurs. If not,  restart the script until it does. Its a game of chance. Or uncomment all the chains and chain head follow all of time. Increases the chances by a lot but floods the logs...

---

```log
➜  light-client-experimental git:(json-rpc-effect-bindings) ✗ ^[OA
pnpm dlx tsx ./scripts/testing.ts
22:28:44 (Fiber #12) INFO  smoldot Smoldot v2.0.25
22:28:44 (Fiber #13) INFO  smoldot Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. Chain specification starting at: 0x9548…ebd3 (#20408370)
22:28:45 (Fiber #15) INFO  json-rpc-provider -> polkadot JSON RPC provider initialized.
22:28:45 (Fiber #21) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-1","method":"rpc_methods","params":[]}
22:28:45 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-1","result":{"methods":["account_nextIndex","author_hasKey","author_hasSessionKeys","author_insertKey","author_pendingExtrinsics","author_removeExtrinsic","author_rotateKeys","author_submitAndWatchExtrinsic","author_submitExtrinsic","author_unwatchExtrinsic","babe_epochAuthorship","chain_getBlock","chain_getBlockHash","chain_getFinalizedHead","chain_getHeader","chain_subscribeAllHeads","chain_subscribeFinalizedHeads","chain_subscribeNewHeads","chain_unsubscribeAllHeads","chain_unsubscribeFinalizedHeads","chain_unsubscribeNewHeads","childstate_getKeys","childstate_getStorage","childstate_getStorageHash","childstate_getStorageSize","grandpa_roundState","offchain_localStorageGet","offchain_localStorageSet","payment_queryInfo","rpc_methods","state_call","state_getKeys","state_getKeysPaged","state_getMetadata","state_getPairs","state_getReadProof","state_getRuntimeVersion","state_getStorage","state_getStorageHash","state_getStorageSize","state_queryStorage","state_queryStorageAt","state_subscribeRuntimeVersion","state_subscribeStorage","state_unsubscribeRuntimeVersion","state_unsubscribeStorage","system_accountNextIndex","system_addReservedPeer","system_chain","system_chainType","system_dryRun","system_health","system_localListenAddresses","system_localPeerId","system_name","system_networkState","system_nodeRoles","system_peers","system_properties","system_removeReservedPeer","system_version","chainHead_v1_body","chainHead_v1_call","chainHead_v1_follow","chainHead_v1_header","chainHead_v1_stopOperation","chainHead_v1_storage","chainHead_v1_continue","chainHead_v1_unfollow","chainHead_v1_unpin","chainSpec_v1_chainName","chainSpec_v1_genesisHash","chainSpec_v1_properties","sudo_unstable_p2pDiscover","sudo_unstable_version","transaction_v1_broadcast","transaction_v1_stop","transactionWatch_v1_submitAndWatch","transactionWatch_v1_unwatch","sudo_network_unstable_watch","sudo_network_unstable_unwatch","chainHead_unstable_finalizedDatabase"]}}
22:28:45 (Fiber #23) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-2","method":"chainHead_v1_follow","params":[true]}
22:28:45 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-2","result":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP"}
22:28:49 (Fiber #34) INFO  runtime-polkadot Finalized block runtime ready. Spec version: 1002000. Size of `:code`: 1.5 MiB.
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"initialized","finalizedBlockHashes":["0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d"],"finalizedBlockRuntime":{"type":"valid","spec":{"specName":"polkadot","implName":"parity-polkadot","specVersion":1002000,"implVersion":0,"transactionVersion":25,"apis":{"0xf78b278be53f454c":2,"0xed99c5acb25eedf5":3,"0xdf6acb689907609b":4,"0x40fe3ad401f8959a":6,"0xd2bc9897eed08f15":3,"0x18ef58a3b67ba770":1,"0x49eaaf1b548a0cb0":3,"0x91d5df18b0d2cf58":2,"0x2a5e924655399e60":1,"0x37c8bb1350a9a2a8":4,"0x37e397fc7c91f5e4":2,"0x17a6bc0d0062aeb3":1,"0xf3ff14d5ab527059":3,"0xbc9d89904f5b923f":1,"0xfbc577b9d747efd6":1,"0xcbca25e39f142387":2,"0xaf2c0297a23e6d3d":10,"0xab3c0572291feb8b":1,"0x687ad44ad37f03c2":1}}}}}}
22:28:49 (Fiber #35) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-3","method":"chainHead_v1_header","params":["JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d"]}
sub! {
  type: 'initialized',
  finalizedBlockHashes: [
    '0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d'
  ],
  finalizedBlockRuntime: {
    type: 'valid',
    spec: {
      specName: 'polkadot',
      implName: 'parity-polkadot',
      specVersion: 1002000,
      implVersion: 0,
      transactionVersion: 25,
      apis: [Object]
    }
  }
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-3","result":"0xd2b0100dc08e1d7624349c8cc09c240faa53c7acfe05cf5fa31fc62b205ebe81be50ec040a37bac92224c212d578cd777c2af3275b4c34e50b990b7cf81e1286627f76e244eb88c866f9e401800bf1089d737b904b30137174a3ecd499670cc5a7cd299f0c0642414245b501011e0100000d600911000000003888cd4656b4d6d06b842400fae22d488363c796d1c202964e914eb31c06c8083fd8b0684ea31b6a1a084109dac2e6f03631cc03759feae0e51a9af07734aa0e4260e0e981233de1bf33ff23cf46ba916c16fe25ca68c5b0546e629ea7bdf30a0442454546840329b4177900bde7b823332072647ad479732e1ab7c018a78d983f6e18322e031205424142450101349392d09097af6c901b1f71b81eb63d2b95a6593bb1cdd6054057dceae0053898b7ba803c94378f5e4d31f32257750565565b6c4a2635006c212121d65f7389"}
22:28:49 (Fiber #36) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-4","method":"chainHead_v1_call","params":["JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d","Metadata_metadata_versions",""]}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-4","result":{"result":"started","operationId":"DtFQfMLNDjhuiS3LWi8RjLmj7SFwMCagdZ26d3aN34nv"}}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"newBlock","blockHash":"0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8","parentBlockHash":"0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d","newRuntime":null}}}
sub! {
  type: 'newBlock',
  blockHash: '0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8',
  parentBlockHash: '0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d',
  newRuntime: null
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"bestBlockChanged","bestBlockHash":"0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8"}}}
sub! {
  type: 'bestBlockChanged',
  bestBlockHash: '0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8'
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"newBlock","blockHash":"0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f","parentBlockHash":"0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8","newRuntime":null}}}
sub! {
  type: 'newBlock',
  blockHash: '0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f',
  parentBlockHash: '0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8',
  newRuntime: null
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"bestBlockChanged","bestBlockHash":"0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f"}}}
sub! {
  type: 'bestBlockChanged',
  bestBlockHash: '0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f'
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"newBlock","blockHash":"0xb357a0c0124e000c16a5b8102a3173b66be43751621f5cd2d4c5ceb36bab4ea5","parentBlockHash":"0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f","newRuntime":null}}}
sub! {
  type: 'newBlock',
  blockHash: '0xb357a0c0124e000c16a5b8102a3173b66be43751621f5cd2d4c5ceb36bab4ea5',
  parentBlockHash: '0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f',
  newRuntime: null
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"bestBlockChanged","bestBlockHash":"0xb357a0c0124e000c16a5b8102a3173b66be43751621f5cd2d4c5ceb36bab4ea5"}}}
sub! {
  type: 'bestBlockChanged',
  bestBlockHash: '0xb357a0c0124e000c16a5b8102a3173b66be43751621f5cd2d4c5ceb36bab4ea5'
}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","result":{"event":"operationCallDone","operationId":"DtFQfMLNDjhuiS3LWi8RjLmj7SFwMCagdZ26d3aN34nv","output":"0x080e0000000f000000"}}}
22:28:49 (Fiber #38) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-5","method":"chainHead_v1_call","params":["JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641d","Metadata_metadata_at_version","0x0f000000"]}
22:28:49 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-5","result":{"result":"started","operationId":"Bo5Tev5NVu6e2QUNFG985i5rteJHWC4G3U1yQQoEyrL4"}}
22:28:49 (Fiber #0) WARN  smoldot Smoldot is restarting...
22:28:49 (Fiber #39) INFO  smoldot Shutting down chain polkadot
22:28:49 (Fiber #14) ERROR json-rpc-provider -> polkadot {"_tag":"AlreadyDestroyedError"}
err! StopError: ChainHead stopped
    at Object.onAllFollowEventsNext (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+substrate-client@0.1.1/node_modules/@polkadot-api/substrate-client/src/chainhead/chainhead.ts:83:21)
    at Object.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+substrate-client@0.1.1/node_modules/@polkadot-api/substrate-client/src/internal-utils/subscriptions-manager.ts:18:30)
    at onMessage (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+substrate-client@0.1.1/node_modules/@polkadot-api/substrate-client/src/client/createClient.ts:91:23)
    at onAbort (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.1.0/node_modules/@polkadot-api/json-rpc-provider-proxy/src/subscription-manager/chainHeadFollow.ts:50:7)
    at Array.forEach (<anonymous>)
    at Object.onAbort (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.1.0/node_modules/@polkadot-api/json-rpc-provider-proxy/src/subscription-manager/subscription-manager.ts:50:18)
    at <anonymous> (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.1.0/node_modules/@polkadot-api/json-rpc-provider-proxy/src/subscription-manager/subscription-manager.ts:80:38)
    at Array.forEach (<anonymous>)
    at Object.onAbort (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.1.0/node_modules/@polkadot-api/json-rpc-provider-proxy/src/subscription-manager/subscription-manager.ts:80:21)
    at onHalt (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.1.0/node_modules/@polkadot-api/json-rpc-provider-proxy/src/get-sync-provider.ts:71:27)
22:28:49 (Fiber #0) INFO  smoldot Smoldot restarted successfully.
22:28:50 (Fiber #42) INFO  smoldot Smoldot v2.0.25
22:28:51 (Fiber #45) INFO  smoldot Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. Chain specification starting at: 0x9548…ebd3 (#20408370)
22:28:51 (Fiber #40) INFO  json-rpc-provider -> polkadot JSON RPC provider initialized.
22:28:51 (Fiber #50) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-6","method":"chainHead_v1_stopOperation","params":["JA9dNg9s2wkgKJH6r8KVGunnFYCP6ffus7yabQ59RyBP","Bo5Tev5NVu6e2QUNFG985i5rteJHWC4G3U1yQQoEyrL4"]}
22:28:51 (Fiber #51) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-7","method":"chainHead_v1_follow","params":[true]}
22:28:51 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-6","result":null}
22:28:51 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-7","result":"2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7"}
22:28:52 (Fiber #57) INFO  runtime-polkadot Finalized block runtime ready. Spec version: 1002000. Size of `:code`: 1.5 MiB.
22:28:52 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7","result":{"event":"initialized","finalizedBlockHashes":["0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8"],"finalizedBlockRuntime":{"type":"valid","spec":{"specName":"polkadot","implName":"parity-polkadot","specVersion":1002000,"implVersion":0,"transactionVersion":25,"apis":{"0xf78b278be53f454c":2,"0xed99c5acb25eedf5":3,"0xdf6acb689907609b":4,"0x40fe3ad401f8959a":6,"0xd2bc9897eed08f15":3,"0x18ef58a3b67ba770":1,"0x49eaaf1b548a0cb0":3,"0x91d5df18b0d2cf58":2,"0x2a5e924655399e60":1,"0x37c8bb1350a9a2a8":4,"0x37e397fc7c91f5e4":2,"0x17a6bc0d0062aeb3":1,"0xf3ff14d5ab527059":3,"0xbc9d89904f5b923f":1,"0xfbc577b9d747efd6":1,"0xcbca25e39f142387":2,"0xaf2c0297a23e6d3d":10,"0xab3c0572291feb8b":1,"0x687ad44ad37f03c2":1}}}}}}
22:28:52 (Fiber #58) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-8","method":"chainHead_v1_header","params":["2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7","0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8"]}
22:28:52 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","id":"1-8","result":"0x880980958b792963b64de923781cc56e497282cd15a5790ea9d18e93fdb6641dc250ec04b6471cc8ed0b109badef44440e38dd769ad489cfc7d1e89df7add6cc4eeea4b85a0ccc10785c8f86247b509896220be5568420ae4cca733bda5743db21d8f4280c0642414245b50103c70000000e6009110000000090bdc1b82233601fd49f9e8842a2bf7eb6e775642f55cfa21508e85a31c5d600a16c8cd5fcc93ad48538ac690a2eb319f132c908504e717480f24061188ad1060fa72dc2750e01e91aa683b8a41bdef007346df68b8ead530a3926ba1539230d044245454684036b360641e79c9323ee7e50a18a958c8a734a926b290552f121ed2e1556959239054241424501015e4b9683959e9090bb0703d2aa259b93d48b2c4e7aa4925794ef7f8e61727d528f003fd048c511b9222ef0a52b4186e39f4957fb4455d5bf93bec177ae1f8e80"}
22:28:53 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7","result":{"event":"newBlock","blockHash":"0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f","parentBlockHash":"0xa621ebc3f640dcf9b9398adea9ac26b8ba1558dea0682c1528117a3bd695fbf8","newRuntime":null}}}
22:28:53 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7","result":{"event":"bestBlockChanged","bestBlockHash":"0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f"}}}
22:28:53 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7","result":{"event":"newBlock","blockHash":"0xb357a0c0124e000c16a5b8102a3173b66be43751621f5cd2d4c5ceb36bab4ea5","parentBlockHash":"0x53ec6d8e1b4ca6a8cca969a539f7f2b7d7af5008705dcac6d1c43364f080ae8f","newRuntime":null}}}
22:28:53 (Fiber #14) DEBUG json-rpc-provider -> polkadot {"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2MBhaD8C6BcDqBfUXEnRdAM76jrLe5Yp8xz7ZAjs7xS7","result":{"event":"bestBlockChanged","bestBlockHash":"0xb357a0c0124e000c16a5b8102a3173b66be43751621f5cd2d4c5ceb36bab4ea5"}}}
/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/reportUnhandledError.ts:21
      throw err;
      ^


BlockNotPinnedError: Block is not pinned
    at Object.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/@polkadot-api+observable-client@0.2.2_rxjs@7.8.1/node_modules/@polkadot-api/observable-client/src/chainHead/enhancers/withStopRecovery.ts:37:30)
    at ConsumerObserver.ConsumerObserver.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at <anonymous> (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subject.ts:68:20)
    at Object.errorContext (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)
    at ReplaySubject.Subject.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subject.ts:61:5)
    at ReplaySubject.ReplaySubject.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/ReplaySubject.ts:65:15)
    at Object.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/share.ts:225:33)
    at ConsumerObserver.ConsumerObserver.next (/home/ryan/Documents/Repositories/substrate-connect/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:161:25)

Node.js v20.12.2
```

**Comment by voliva** [comment]
Thanks for opening the issue.

From the logs with that reproduction I see it's after a stop event recovery, there was an operation on a block that after recovering isn't there anymore (thus we throw BlockNotPinned).

But the only operation I see ongoing when the stop happens is `Metadata_metadata_at_version`, which polkadot-api sends to get the runtime. I think on this case we want to repeat the operation with the new finalized block.

**Comment by josepot** [comment]
IIRC the stop recovery logic only kicks in after we have received the first runtime. In other words, I'm pretty sure that we determined that it was not really worth it to try to recover from a stop event if it happened before we were able to compute the first runtime-context, due to the fact that it added a lot of super-complicated complexity.

Therefore, if the stop event happened before we were able to get the metadata response, then I think that it's to be expected that we can't recover from it.

If what I'm saying is correct, I would say that this issue should be considered a very low priority issue, because realistically speaking this is something that will only happen in a completely artificial environment.

**Comment by ryanleecode** [comment]
I wouldnt say its only possible in a completely artificial environment.

Smoldot can crash while you are fetching the metadata. And the crash could be caused by other chains connected to smoldot that are already in their "post fetch metadata" stage.

**Comment by ryanleecode** [comment]
Also I dont understand since in the logs I provided its already past the finalized block runtime stage

**Comment by josepot** [comment]
> I wouldnt say its only possible in a completely artificial environment.
> 
> Smoldot can crash while you are fetching the metadata. And the crash could be caused by other chains connected to smoldot that are already in their "post fetch metadata" stage.

That would clearly be a bug on smoldot. Smoldot should not send a stop event because it crashed while fetching the metadata.

> Also I dont understand since in the logs I provided its already past the finalized block runtime stage

The comment was addressed to @voliva. The runtime context is all the stuff that we need to be able to start creating operations and what not, it's an internal concept. The runtime context is basically computed once we have the metadata of the current runtime.
