### ISSUE TITLE
Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#632]
Seems like this not nullable assertion is incorrect.

https://github.com/polkadot-api/polkadot-api/blob/62690e91866426b80d4ea0f7489c15955f8ff9f3/packages/client/src/tx/submit-fns.ts#L70

```
➜  identity-backend git:(dev) ✗ corepack pnpm dlx tsx ./test.ts

Packages: +5
+++++
Progress: resolved 29, reused 5, downloaded 0, added 5, done
{
  type: 'signed',
  txHash: '0x0b1aa8df09dda67fcae601441ddd19c6ea6929a5344fd666b2b96afe91faa9e5'
}
{
  type: 'broadcasted',
  txHash: '0x0b1aa8df09dda67fcae601441ddd19c6ea6929a5344fd666b2b96afe91faa9e5'
}
{
  type: 'txBestBlocksState',
  txHash: '0x0b1aa8df09dda67fcae601441ddd19c6ea6929a5344fd666b2b96afe91faa9e5',
  found: true,
  block: {
    index: 2,
    number: 2416574,
    hash: '0xa06dc8a2dfad4aaaa1d0b12375084532caae932ee45ca24f432155f450251115'
  },
  ok: true,
  events: [
    { type: 'Balances', value: [Object] },
    { type: 'Identity', value: [Object] },
    { type: 'Balances', value: [Object] },
    { type: 'Balances', value: [Object] },
    { type: 'TransactionPayment', value: [Object] },
    { type: 'System', value: [Object] }
  ]
}
/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/reportUnhandledError.ts:21
      throw err;
      ^


TypeError: Cannot read properties of undefined (reading 'number')
    at computeNextState (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/polkadot-api@0.12.1_rxjs@7.8.1_smoldot@2.0.29_yaml@2.5.0/node_modules/polkadot-api/src/tx/submit-fns.ts:70:70)
    at Object.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/polkadot-api@0.12.1_rxjs@7.8.1_smoldot@2.0.29_yaml@2.5.0/node_modules/polkadot-api/src/tx/submit-fns.ts:113:28)
    at ConsumerObserver.ConsumerObserver.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/distinctUntilChanged.ts:173:22)
    at OperatorSubscriber.OperatorSubscriber._this._next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subject.ts:68:20)
    at Object.errorContext (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)

Node.js v20.12.2
```

**Comment by josepot** [comment]
weird 🤔 

And this happened with the latest version of polkadot-api?

I will look into this. Something that would be really helpful, though would be if you could please use the [`withLogsRecorder`](https://github.com/polkadot-api/polkadot-api/tree/main/packages/json-rpc/logs-provider#withlogsrecorder) to capture the "wire" logs in case you are able to reproduce this again.

Otherwise, have you found a somewhat way to reproduce this? 🙏

**Comment by ryanleecode** [comment]
Was on `0.12.1`. Tried again with `0.13.2` was able to repro

repo: https://gist.github.com/ryanleecode/bb83299e1a49b455d84e066827ebe245
logs: https://gist.github.com/ryanleecode/db5284ade75918f7f33b63a578e56824
