### ISSUE TITLE
InvalidTxError: {   "type": "Invalid",   "value": {     "type": "Stale"   } }

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#634]
PAPI version: 0.13.2
Repo: https://github.com/ryanleecode/papi-test
Logs: https://gist.github.com/ryanleecode/2a8a93e8d05bd367108a9b991f28a82e

Might be hard to repo the with the exact same script but it probably applies to any `signSubmitWatch` workflow. Also it doesn't happen every time. 

```
➜  identity-backend git:(dev) ✗ corepack pnpm dlx tsx ./test.ts
{
  type: 'signed',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3'
}
{
  type: 'broadcasted',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3'
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
{
  type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/reportUnhandledError.ts:21
      throw err;
      ^


InvalidTxError: {
  "type": "Invalid",
  "value": {
    "type": "Stale"
  }
}
    at computeNextState (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/polkadot-api@0.13.2_rxjs@7.8.1_smoldot@2.0.29_yaml@2.5.0/node_modules/polkadot-api/src/tx/submit-fns.ts:99:26)
    at Object.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/polkadot-api@0.13.2_rxjs@7.8.1_smoldot@2.0.29_yaml@2.5.0/node_modules/polkadot-api/src/tx/submit-fns.ts:113:28)
    at ConsumerObserver.ConsumerObserver.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
    at SafeSubscriber.Subscriber.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/distinctUntilChanged.ts:173:22)
    at OperatorSubscriber.OperatorSubscriber._this._next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/Subject.ts:68:20)
    at Object.errorContext (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/src/internal/util/errorContext.ts:29:5) {
  error: { type: 'Invalid', value: { type: 'Stale', value: undefined } }
}

Node.js v20.12.2
```

**Comment by voliva** [comment]
I'm investigating #632 and I could reproduce this, but I think it's intended behaviour.

The transaction is broadcasted, but if it's not included in a block soon enough, it becomes stale. Once a finalised block marks it as stale, then we throw the `InvalidTxError` because the transaction is invalid (an it's actually finalised).

**Comment by ryanleecode** [comment]
So if i see

```js
(
type: 'txBestBlocksState',
  txHash: '0xaca526ac2ff9625d0e4208904c15775589d3208b4a8355f9bfc1c1861abcc3a3',
  found: false,
  isValid: false
}
```

i should abort and retry?

**Comment by voliva** [comment]
Yes, but I was wrong - A stale error is reported when the `nonce` doesn't match (probably when the same account is doing many transactions at the same time and some nonce collided)

https://wiki.polkadot.network/docs/maintain-errors#common-errors
