### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#710]
While trying to debug sudden crashes of faucet, caught this in a minimal repro example. It actually took more that a day of running:
```
/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70
            onNext(value);
            ^
TypeError: Cannot read properties of undefined (reading 'number')
    at /Users/cornholio/work/parity/papi-repro/node_modules/@polkadot-api/observable-client/src/chainHead/streams/pinned-blocks.ts:200:34
    at /Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/operators/scanInternals.ts:43:15
    at OperatorSubscriber._this._next (/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at /Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/operators/mergeInternals.ts:85:24
    at OperatorSubscriber._this._next (/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at Object.next (/Users/cornholio/work/parity/papi-repro/node_modules/@polkadot-api/observable-client/src/chainHead/streams/follow.ts:54:33)
    at ConsumerObserver.next (/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/Subscriber.ts:161:25)
    at SafeSubscriber.Subscriber._next (/Users/cornholio/work/parity/papi-repro/node_modules/rxjs/src/internal/Subscriber.ts:119:22)
error Command failed with exit code 1.
```
But we do see crashes with this error in faucet. 

Can we do some kind of error recovery on papi side, so this would show a warning, but wouldn't crash an app? 

[papi-debug-relay.log](https://github.com/user-attachments/files/16976299/papi-debug-relay.log)
[papi-repro.tar.gz](https://github.com/user-attachments/files/16976316/papi-repro.tar.gz)

**Comment by josepot** [comment]
Thanks for opening this issue @mutantcornholio.

This is in fact a dup of #671, meaning that this is [an issue with the polkadot-sdk node](https://github.com/paritytech/polkadot-sdk/issues/5512). We released an enhancer to prevent this from happening on [version 1.2.0](https://github.com/polkadot-api/polkadot-api/releases/tag/polkadot-api%401.2.0). So, using the `withPolkadotSdkCompat` enhancer should prevent this problem from happening.

You can see it clearly in the logs:

```
1-2024-09-11T21:13:54.228Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"VNVkc68FrHBYlRKo","result":{"event":"bestBlockChanged","bestBlockHash":"0xf368631c19f7d6a91cfbbb856ab4516224febc4f65609284ce0b45a77f8d4cd3"}}}
1-2024-09-11T21:14:00.336Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"VNVkc68FrHBYlRKo","result":{"event":"bestBlockChanged","bestBlockHash":"0x198235944e5242497afec1c5a63d2c844c0f4cca11e4bd4029c2892affa1f4a5"}}}
1-2024-09-11T21:14:00.380Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"VNVkc68FrHBYlRKo","result":{"event":"finalized","finalizedBlockHashes":["0x48d1f8783d8718678ca98a81c2d6d909d217a676f387733342aceaa20848a21b"],"prunedBlockHashes":[]}}}
1-2024-09-11T21:14:00.380Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"VNVkc68FrHBYlRKo","result":{"event":"newBlock","blockHash":"0x198235944e5242497afec1c5a63d2c844c0f4cca11e4bd4029c2892affa1f4a5","parentBlockHash":"0xf368631c19f7d6a91cfbbb856ab4516224febc4f65609284ce0b45a77f8d4cd3","newRuntime":null}}}
```
the `bestBlockChanged` for block `0x198235944e5242497afec1c5a63d2c844c0f4cca11e4bd4029c2892affa1f4a5` is emitted before the block has been announced.

> Can we do some kind of error recovery on papi side, so this would show a warning, but wouldn't crash an app?

it's pretty difficult, but I will put some thought into this.
