### ISSUE TITLE
'onGoingRequests.values().forEach' is undefined

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#770]
`onGoingRequests.values().forEach` doesnt work in Bun.

## Repro

```sh
bun repl
new Map().values().forEach((x)=>{})
// TypeError: new Map().values().forEach is not a function. (In 'new Map().values().forEach((x)=>{})', 'new Map().values().forEach' is undefined)


```

## Logs

```
2024-10-04 10:17:37.869	error: script "start" exited with code 1
2024-10-04 10:17:37.857	error: script "start" exited with code 1
2024-10-04 10:17:37.833	Bun v1.1.29 (Linux x64 baseline)
2024-10-04 10:17:37.833	
2024-10-04 10:17:37.832	      at /usr/src/app/node_modules/@polkadot-api/ws-provider/dist/web/esm/ws-provider.mjs:92:11
2024-10-04 10:17:37.832	      at /usr/src/app/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-sync-provider.mjs:21:15
2024-10-04 10:17:37.832	      at /usr/src/app/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-proxy.mjs:76:34
2024-10-04 10:17:37.832	          })', 'onGoingRequests.values().forEach' is undefined)
2024-10-04 10:17:37.832	              send(x.msg);
2024-10-04 10:17:37.832	            else
2024-10-04 10:17:37.832	              }));
2024-10-04 10:17:37.832	                internal: !0
2024-10-04 10:17:37.832	                error: { code: -32603, message: "Internal error" },
2024-10-04 10:17:37.832	                id: x.id,
2024-10-04 10:17:37.832	              onMsgFromProvider(jsonRpcMsg({
2024-10-04 10:17:37.832	            if (x.type === 1)
2024-10-04 10:17:37.832	TypeError: onGoingRequests.values().forEach is not a function. (In 'onGoingRequests.values().forEach((x) => {
2024-10-04 10:17:37.832	                                      ^
2024-10-04 10:17:37.832	76 |         onGoingRequests.values().forEach((x) => {
2024-10-04 10:17:37.832	75 |         activeChainHeads.clear();
2024-10-04 10:17:37.832	74 |         });
2024-10-04 10:17:37.832	73 |           );
2024-10-04 10:17:37.832	72 |             })
2024-10-04 10:17:37.832	71 |               }
2024-10-04 10:17:37.831	Bun v1.1.29 (Linux x64 baseline)
2024-10-04 10:17:37.831	
2024-10-04 10:17:37.831	      at /usr/src/app/node_modules/@polkadot-api/ws-provider/dist/web/esm/ws-provider.mjs:92:11
2024-10-04 10:17:37.831	      at /usr/src/app/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-sync-provider.mjs:21:15
2024-10-04 10:17:37.831	      at /usr/src/app/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-proxy.mjs:76:34
2024-10-04 10:17:37.831	          })', 'onGoingRequests.values().forEach' is undefined)
2024-10-04 10:17:37.831	              send(x.msg);
2024-10-04 10:17:37.831	            else
2024-10-04 10:17:37.831	              }));
2024-10-04 10:17:37.831	                internal: !0
2024-10-04 10:17:37.831	                error: { code: -32603, message: "Internal error" },
2024-10-04 10:17:37.831	                id: x.id,
2024-10-04 10:17:37.831	              onMsgFromProvider(jsonRpcMsg({
2024-10-04 10:17:37.831	            if (x.type === 1)
2024-10-04 10:17:37.831	TypeError: onGoingRequests.values().forEach is not a function. (In 'onGoingRequests.values().forEach((x) => {
2024-10-04 10:17:37.831	                                      ^
2024-10-04 10:17:37.831	76 |         onGoingRequests.values().forEach((x) => {
2024-10-04 10:17:37.831	75 |         activeChainHeads.clear();
2024-10-04 10:17:37.831	74 |         });
2024-10-04 10:17:37.831	73 |           );
2024-10-04 10:17:37.831	72 |             })
2024-10-04 10:17:37.831	71 |               }
2024-10-04 10:17:37.831	WS halt (3)
2024-10-04 10:17:37.829	WS halt (3)
2024-10-04 10:17:37.819	error: script "start" exited with code 1
```

**Comment by carlosala** [comment]
Actually it is not available on Node LTS and in firefox neither. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/forEach

We should look at it. Thanks for the report!

**Comment by carlosala** [comment]
We will target `lib` es2023 from now on. It will be solved in next PAPI release. Thanks!

**Comment by ryanleecode** [comment]
Looks like it will be added soon.

https://x.com/bunjavascript/status/1844936747773460728?t=bsZVZo4csc6elElWofNcLg&s=19
