### ISSUE TITLE
🚨 Cannot build project with latest because polkadot-api requires ink-contracts...

### ISSUE THREAD

**Issue by decentration** [polkadot-api/polkadot-api#787]
if i yarn add `polkadot-api` with latest, i get :

```
[1/4] 🔍  Resolving packages...
error Couldn't find package "@polkadot-api/ink-contracts@0.0.1" required by "@polkadot-api/codegen@0.12.4" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Couldn't find package "@polkadot-api/ink-contracts@0.0.1" required by "polkadot-api" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:721:66)
    at new MessageError (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:36620:17)
    at Generator.throw (<anonymous>)
    at step (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:310:30)
    at /Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Error: Couldn't find package "@polkadot-api/ink-contracts@0.0.1" required by "@polkadot-api/cli@0.9.6" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:721:66)
    at new MessageError (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:36620:17)
    at Generator.throw (<anonymous>)
    at step (/Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:310:30)
    at /Users/ramsey/.cache/node/corepack/v1/yarn/1.22.22/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
   
   ```
    
 however it looks like it works for `1.4.1`, probably needs emergency update else all the `latest` builds will fail like this.

**Comment by voliva** [comment]
Thanks for the report! We haven't fully released ink support yet, but there's a codegen part that was merged, so it does need that dependency.

Fix incomming publishing the new package.
