### ISSUE TITLE
BlockNotPinnedError: Block is not pinned crash on Westend

### ISSUE THREAD

**Issue by mutantcornholio** [polkadot-api/polkadot-api#804]
With papi@1.6.1, we're experiencing these crashes on Westend (and not on Paseo):
```
2024-10-18 10:06:59.452 | at ConsumerObserver.next (/faucet/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33) |  

2024-10-18 10:06:59.452 | at Object.next (/faucet/node_modules/rxjs/dist/cjs/internal/operators/share.js:69:58) |  
2024-10-18 10:06:59.452 | at ReplaySubject.next (/faucet/node_modules/rxjs/dist/cjs/internal/ReplaySubject.js:45:31) |  
2024-10-18 10:06:59.452 | at Subject.next (/faucet/node_modules/rxjs/dist/cjs/internal/Subject.js:59:24) |  
2024-10-18 10:06:59.452 | at Object.errorContext (/faucet/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9) |  
2024-10-18 10:06:59.452 | at /faucet/node_modules/rxjs/dist/cjs/internal/Subject.js:69:34 |  
2024-10-18 10:06:59.452 | at Subscriber.next (/faucet/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18) |  
2024-10-18 10:06:59.452 | at Subscriber._next (/faucet/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26) |  
2024-10-18 10:06:59.452 | at ConsumerObserver.next (/faucet/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33) |  
2024-10-18 10:06:59.452 | at Object.next (/faucet/node_modules/@polkadot-api/observable-client/dist/index.js:411:30) |  
2024-10-18 10:06:59.452 | BlockNotPinnedError: Block is not pinned |  
2024-10-18 10:06:59.452 |
2024-10-18 10:06:59.452 |
2024-10-18 10:06:59.452 | observer.error(new BlockNotPinnedError()); |  
2024-10-18 10:06:59.452 | /faucet/node_modules/@polkadot-api/observable-client/dist/index.js:411

```

**Comment by josepot** [comment]
> The error comes from here
> 
> https://github.com/polkadot-api/polkadot-api/blob/ddacad1e9f356e746e3f7ae16c26fa7436fdbbc7/packages/observable-client/src/chainHead/enhancers/withStopRecovery.ts#L37

I know what's triggering the error on our side. What I'm asking is the code on the user's side.

**Comment by mutantcornholio** [comment]
Judging by the logs, it just happened on its own.
