### ISSUE TITLE
[u8; 32] pallet call parameter causing error

### ISSUE THREAD

**Issue by kukabi** [polkadot-api/polkadot-api#809]
Hi guys,

I have a call in my pallet as the following:

```rust
#[pallet::call_index(5)]
#[pallet::weight(T::WeightInfo::transfer_collectible())]
pub fn transfer_collectible(
    origin: OriginFor<T>,
    collectible_id: [u8; 32],
    to: T::AccountId,
) -> DispatchResult {
    // ...
}
```

The corresponding API function property generated by PAPI looks like:

```typescript
(property) transfer_collectible: (data: {
    collectible_id: FixedSizeBinary<32>;
    to: SS58String;
}) => Transaction<...>
```

When I try to make a call as the following:

```typescript
const tx = this.api.tx.MyPallet.transfer_collectible({
    collectible_id: collectible.id, // type of collectible.id is FixedSizeBinary<32>
    to: address,
});
const payload = await tx.signAndSubmit(this.signer);
```

I get the following error before the call gets dispatched to the RPC node:

```
TypeError: value.asBytes is not a function
    at eval (Binary.mjs:92:32)
    at eval (scale-ts.js:365:83)
    at Array.map (<anonymous>)
    at eval (scale-ts.js:365:65)
    at Array.eval [as enc] (scale-ts.js:124:54)
    at getCallDataWithContext (tx.mjs:74:107)
    at eval (tx.mjs:80:64)
    at eval (map.js:13:37)
    at OperatorSubscriber._this._next (OperatorSubscriber.js:22:21)
    at Subscriber.next (Subscriber.js:49:18)
```

The error seems to be related to the `[u8; 32]` parameter. I'm using version `1.6.2`.
Is there anything I can do to fix this?

Thanks.

**Comment by kukabi** [comment]
Closing. It was due to an internal data conversion error.
