### ISSUE TITLE
chainhead does not work if `withRuntime` is set to false with smoldot

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-api/polkadot-api#815]
Repro: https://stackblitz.com/edit/node-75ky53?file=src%2Findex.ts

```log
❯ pnpm dlx tsx ./src/index.ts
Packages: +5
+++++
Progress: resolved 29, reused 5, downloaded 0, added 5, done
[smoldot] Smoldot v2.0.30
[smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. Chain specification starting at: 0x9fed…747b (#23003139)
{
  type: 'initialized',
  finalizedBlockHashes: [
    '0x9fedebd87e586cbd4ed1b5131eb582eba4680422251c2e17626f1861aa23747b'
  ],
  finalizedBlockRuntime: undefined
}
StopError: ChainHead stopped
    at new StopError (file:///home/projects/node-glcjhe/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/chainhead/errors.mjs:20:5)
    at Object.onAllFollowEventsNext (file:///home/projects/node-glcjhe/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/chainhead/chainhead.mjs:56:21)
    at Object.next (file:///home/projects/node-glcjhe/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/internal-utils/subscriptions-manager.mjs:25:30)
    at onMessage (file:///home/projects/node-glcjhe/node_modules/.pnpm/@polkadot-api+substrate-client@0.2.2/node_modules/@polkadot-api/substrate-client/dist/esm/client/createClient.mjs:61:23)
    at onMsgFromProvider (file:///home/projects/node-glcjhe/node_modules/.pnpm/@polkadot-api+json-rpc-provider-proxy@0.2.3/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-proxy.mjs:39:38)
    at eval (file:///home/projects/node-glcjhe/node_modules/.pnpm/@polkadot-api+sm-provider@0.1.3_smoldot@2.0.30/node_modules/@polkadot-api/sm-provider/dist/esm/sm-provider.mjs:39:9)
[runtime-polkadot] Finalized block runtime ready. Spec version: 1003003. Size of `:code`: 1.7 MiB.
```

**Comment by voliva** [comment]
This is something I've seen before, it's by design of the JSON-RPC spec. Adding `withLogsRecorder` you can see a `stop` notification is coming from smoldot:

```ts
1-2024-10-22T22:03:31.617Z->>-{"jsonrpc":"2.0","id":"1-1","method":"chainHead_v1_follow","params":[false]}
1-2024-10-22T22:03:31.617Z-<<-{"jsonrpc":"2.0","id":"1-1","result":"2Gn51gah4xYfCWiYnJMv5GmNMi8EcKEZukEyfztZAR64"}
1-2024-10-22T22:03:31.617Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2Gn51gah4xYfCWiYnJMv5GmNMi8EcKEZukEyfztZAR64","result":{"event":"initialized","finalizedBlockHashes":["0x9fedebd87e586cbd4ed1b5131eb582eba4680422251c2e17626f1861aa23747b"]}}}
1-2024-10-22T22:03:33.487Z-<<-{"jsonrpc":"2.0","method":"chainHead_v1_followEvent","params":{"subscription":"2Gn51gah4xYfCWiYnJMv5GmNMi8EcKEZukEyfztZAR64","result":{"event":"stop"}}}
```

You can read more in the issue I opened in smoldot when I thought this was a bug: https://github.com/smol-dot/smoldot/issues/1665. tl;dr; running with `withRuntime=false` will initially give the latest known valid block w/o waiting for the runtime to be loaded, but as it connects to new nodes and receives blocks which are disconnected from that one, then it emits a `stop` event because it can't really connect them. And this can also happen with `withRuntime=true`, but it's unlikely.

You can then retry after reciving the stop event, and you should be getting the latest blocks. And at the level you're working at (substrate-client), you have to do that by yourself, as this library is pretty much unopinionated past the JSON-RPC spec.
